version: '3.8'

services:
  db:
    image: postgres:15
    container_name: quiniela_db
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quiniela_mundial
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
